### ISSUE TITLE
Instalación en *buntu/Mint

### ISSUE THREAD

**Issue by da-rodriguez** [HuayraLinux/huayra-tpm#2]
Alguien me puede decir si es posible que el TPM funcione en la última versión de *buntu/Mint

El problema se da con una dependencia, libssl1.0.0. La versión que está disponible es la libssl1.1

Razón?, pues básicamente tener el sistema lo más actualizado posible en las netbooks que aún funcionan.

**Comment by ftoledo** [comment]
Esta version funciona en las que esten basadas en jessie, efectivamente con libssl1.0.0 

Para derivadas de stretch usa este otro: https://github.com/HuayraLinux/theftdeterrent4

Estamos en camino de tener una version que funcione en Huayra 5 que esta basada en buster
